import { test, expect } from '@playwright/test';
import fs from 'node:fs/promises';
test('import, real Stockfish analysis, navigation, notes, export and session restore', async ({ page }, testInfo) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Import PGN', exact: true }).click();
  await page.getByLabel('PGN game', { exact: true }).fill('[White "Alice"]\n[Black "Bob"]\n\n1. f3 e5 2. g4 Qh4# 0-1');
  await page.getByRole('button', { name: 'Load PGN', exact: true }).click();
  await page.getByRole('button', { name: 'Analyze', exact: true }).click();
  await expect(page.getByText('Analysis complete', { exact: true })).toBeVisible({ timeout: 30000 });
  await expect(page.locator('.review-scores strong')).toHaveCount(2);
  await page.getByRole('button', { name: 'Last position', exact: true }).click();
  await expect(page.getByText('Black wins by checkmate', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit position note', exact: true }).click();
  await page.getByLabel('Position note', { exact: true }).fill('Watch the diagonal!');
  await page.getByLabel('Position note', { exact: true }).press('ArrowLeft');
  await expect(page.getByLabel('Position note', { exact: true })).toHaveValue('Watch the diagonal!');
  const pending = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export PGN', exact: true }).click();
  const file = await pending; const pgn = await fs.readFile(await file.path(), 'utf8');
  expect(pgn).toContain('{Watch the diagonal!}');
  await page.screenshot({ path: testInfo.outputPath('review-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('review-mobile.png'), fullPage: true });
  await page.reload();
  await page.getByRole('button', { name: 'Import PGN', exact: true }).click();
  await page.getByRole('button', { name: 'Restore last review', exact: true }).click();
  await page.getByRole('button', { name: 'Last position', exact: true }).click();
  await expect(page.getByText('Watch the diagonal!', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Analyze', exact: true }).click();
  await page.getByRole('button', { name: 'Cancel analysis', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Analyze', exact: true })).toBeEnabled();
  expect(errors).toEqual([]);
});
